import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/index";
import Sidebar from "@/components/sidebar/index";
import AsideBar from "@/components/asidebar/index";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen max-w-[100%] flex font-sans">
        {/* <!-- Sidebar --> */}
        <div className="h-full lg:w-72">
          <Sidebar />
        </div>

        <div className="flex flex-col w-full gap-3 flex-grow">
          {/* <!-- Header --> */}
          <nav className="h-16 w-full py-3">
            <Navbar />
          </nav>

          <div className="block md:flex">
            {/* <!-- Main Content --> */}
            <main className="pt-5">
              {children}
            </main>

            {/* <!-- Aside --> */}
            <aside className="h-full lg:hidden xl:w-[350px] flex-shrink-0">
              <AsideBar />
            </aside>
          </div>
        </div>

        {/* <!-- Footer --> */}
        <footer className="fixed w-full bottom-0">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
